# Complete Pandas Lab Notebook

This clean notebook contains the
**entire Week 2 Pandas and Dataset Inspection lab manual first**,
followed by the **entire Advanced Pandas lab manual**.

**Order:**
1. Week 2 — Inspection for AI
2. Advanced Pandas

### WEEK 2 - Programming for AI

## 1. Lab Overview

```text
Dataset → Load → Inspect → Understand → Check problems → Prepare → Model
```

## 2. Learning Outcomes

- Explain why Pandas is useful in AI.

- Create Pandas Series and DataFrames.

- Understand rows, columns, and index.

- Create, save, and load CSV datasets.

- Create, save, and load JSON datasets.

- Use relative and absolute dataset paths.

- Use head(), tail(), shape, columns, info(), and describe().

- Understand common Pandas data types.

- Check missing values and duplicate rows.

- Select columns and filter rows.

- Sort data and make a simple inspection report.

- Explain why dataset inspection is important before AI modeling.

## 3. Setup

In [ ]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.3

### Task 1: First Pandas Series

Goal: Create a Series from five marks.

Example:

In [ ]:
marks = pd.Series([65,70,80,90,75])
print(marks)

0    65
1    70
2    80
3    90
4    75
dtype: int64

Check your work:

- How many values are shown?

- What is the index?

Goal: Calculate the average, minimum, and maximum.

Example:

In [ ]:
scores = pd.Series([72,88,91,65,79])
print(scores.mean())
print(scores.min())
print(scores.max())

79.0
65
91

Check your work:

- What is the average?

- Which value is highest?

__________

In [ ]:
numbers = pd.Series([1,2,3,4,5])

In [ ]:
len(numbers)

5

In [ ]:
print(numbers.index)

RangeIndex(start=0, stop=5, step=1)

In [ ]:
print(numbers.values)

[1 2 3 4 5]

In [ ]:
numbers.max()

5

In [ ]:
numbers.min()

1

In [ ]:
int(numbers.mean())

3

## 4. Pandas Series

A Series is a one-dimensional Pandas object. It is similar to one column of data with an index.

In [ ]:
marks = pd.Series([65,70,80], index=['Ali','Sara','John'])
# print(marks)
print(marks['Sara'])

70

In [ ]:
print(marks)

Ali     65
Sara    70
John    80
dtype: int64

The index helps us identify values. It can use default numbers or labels.

### Task 2: Labeled Series

Goal: Create a Series using student names as labels.

Example:

In [ ]:
scores = pd.Series([72,88,91], index=['Ali','Sara','Ayesha'])
print(scores)
print(scores['Sara'])

Ali       72
Sara      88
Ayesha    91
dtype: int64
88

Check your work:

- What is Sara's score?

- What are the index labels?

__________

In [ ]:
age = pd.Series([25,30,22], index=['Ali','Sara','Ayesha'])

In [ ]:
int(age["Sara"])

30

In [ ]:
print(age.index)

Index(['Ali', 'Sara', 'Ayesha'], dtype='object')

## 5. DataFrames

A DataFrame is a table with rows and columns. AI datasets are commonly represented as DataFrames during data preparation.

In [ ]:
data = {
    'name':['Ali','Sara','John','Ayesha'],
    'study_hours':[3,5,2,6],
    'attendance':[75,90,70,95],
    'exam_score':[65,88,58,94]
}
df = pd.DataFrame(data)
print(df)

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94

### Rows, Columns, and Index

- A row is one record, such as one student.

- A column stores one variable or feature.

- The index identifies row positions.

- Clear column names make data easier to understand.

In [ ]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [ ]:
print(df.columns)

Index(['name', 'study_hours', 'attendance', 'exam_score'], dtype='object')

In [ ]:
print(df['exam_score'])

0    65
1    88
2    58
3    94
Name: exam_score, dtype: int64

### Task 3: Create a DataFrame

Goal: Create and display a four-student DataFrame.

Example:

In [ ]:
print(df)
print('\nRows:',len(df))
print('Columns:',len(df.columns))

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94

Rows: 4
Columns: 4

Check your work:

- How many rows?

- How many columns?

__________

In [ ]:
s_df = pd.DataFrame({
    "cloumn1": [1, 2, 3, 4],
    "column2": ["A", "B", "C", "D"]
})

In [ ]:
print(s_df)

   cloumn1 column2
0        1       A
1        2       B
2        3       C
3        4       D

In [ ]:
len(numbers)

5

In [ ]:
print(len(df.columns))

4

### Task 4: Inspect Index and Columns

Goal: Display the index and column names.

Example:

In [ ]:
print('Index:',df.index)
print('\nColumns:',list(df.columns))

Index: RangeIndex(start=0, stop=4, step=1)

Columns: ['name', 'study_hours', 'attendance', 'exam_score']

Check your work:

- Write the column names.

__________

In [ ]:
print(s_df.index)

RangeIndex(start=0, stop=4, step=1)

In [ ]:
print(s_df.columns)

Index(['cloumn1', 'column2'], dtype='object')

## 6. CSV Datasets

CSV means Comma-Separated Values. It is a common format for tabular datasets.

In [ ]:
%%file students.csv
student_id,name,study_hours,attendance,exam_score
STU001,Ali,3,75,65
STU002,Sara,5,90,88
STU003,John,2,70,58
STU004,Ayesha,6,95,94

Overwriting students.csv

### Save and Load CSV

In [ ]:
df.to_csv('students.csv', index=False)
df2 = pd.read_csv('students.csv')
print(df2)

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94

### Task 5 Save CSV

Goal: Save your DataFrame as students.csv.

Example:

In [ ]:
df.to_csv('students.csv',index=False)
print('Saved')

Saved

Check your work:

- Was the file created?

- Why use index=False?

__________

- students.csv
- so that indexes arent stored in the csv

### Task 6: Load CSV

Goal: Load students.csv with Pandas.

Example:

In [ ]:
df2=pd.read_csv('students.csv')
print(df2)

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94

Check your work:

- Does it match the original table?

__________

yes

## 7. Dataset Paths

A path tells Python where a dataset is located.

In [ ]:
df = pd.read_csv('students.csv')
df = pd.read_csv('C:/Users/HP/Documents/Github/Machine-Learning/Programming-for-AI/students.csv')

In [ ]:
print(df)

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94

Windows example:

In [ ]:
df = pd.read_csv('C:/Users/HP/Documents/Github/Machine-Learning/Programming-for-AI/students.csv')

Linux/macOS example:

In [ ]:
df = pd.read_csv('/home/hammad/Documents/Github/Machine-Learning/Programming-for-AI/students.csv')

### Task 7: Practice Paths

Goal: Read a file from a data folder.

Example:

In [ ]:
df=pd.read_csv('students.csv')
print(df.head())

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94

In [ ]:
list(df)

['name', 'study_hours', 'attendance', 'exam_score']

Check your work:

- What does students.csv mean?

- What happens if the file is missing?

__________

In [ ]:
!mkdir data

In [ ]:
%%file data/students.csv
3,3,3,3
d,d,d,d

Overwriting data/students.csv

In [ ]:
d=pd.read_csv('data/students.csv')

In [ ]:
print(d)

   3 3.1 3.2 3.3
0  d   d   d   d

- it is the path of the file
- throws an error if the file is not found

## 8. JSON Datasets

JSON is common in web applications and APIs. Pandas can read many JSON dataset structures.

In [ ]:
[
 {"name":"Ali","age":20,"score":72},
 {"name":"Sara","age":21,"score":88},
 {"name":"John","age":19,"score":65}
]

[{'name': 'Ali', 'age': 20, 'score': 72},
 {'name': 'Sara', 'age': 21, 'score': 88},
 {'name': 'John', 'age': 19, 'score': 65}]

In [ ]:
ls = [
    {"brand":"toyota","model":"grende","make":2017},
    {"brand":"honda","model":"civic","make":2010},
    {"brand":"suzuki","model":"swift","make":2015}
]

In [ ]:
list(df)

['name', 'study_hours', 'attendance', 'exam_score']

In [ ]:
ls=pd.DataFrame(ls)

In [ ]:
df.to_json('students.json',orient='records',indent=2)
df_json=pd.read_json('students.json')
print(df_json)

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94

In [ ]:
ls.to_json("cars.json",orient='records',indent=20)

In [ ]:
r = pd.read_json("cars.json")

In [ ]:
print(r)

    brand   model  make
0  toyota  grende  2017
1   honda   civic  2010
2  suzuki   swift  2015

### Task 8: Create JSON

Goal: Save a DataFrame as JSON.

Example:

In [ ]:
df.to_json('students.json',orient='records',indent=2)
print('Saved JSON')

Saved JSON

Check your work:

- Was the JSON file created?

__________

- yes

### Task 9: Load JSON

Goal: Load the JSON file into a DataFrame.

Example:

In [ ]:
df_json=pd.read_json('students.json')
print(df_json)

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94

Check your work:

- How many rows?

- What are the columns?

__________

4 x 4

## 9. head()

head() displays the first five rows by default. It is one of the first commands to use when receiving a new dataset.

In [ ]:
print(df.head())

print('\n\n', df.head(2))

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94


    name  study_hours  attendance  exam_score
0   Ali            3          75          65
1  Sara            5          90          88

### Task 10: Use head

Goal: Display the first three rows.

Example:

In [ ]:
print(df.head(3))

   name  study_hours  attendance  exam_score
0   Ali            3          75          65
1  Sara            5          90          88
2  John            2          70          58

Check your work:

- How many rows are shown?

__________

3

## 10. tail()

tail() displays the last five rows by default.

In [ ]:
print(df.tail())
print('\n\n', df.tail(2))

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94


      name  study_hours  attendance  exam_score
2    John            2          70          58
3  Ayesha            6          95          94

### Task 11: Use tail

Goal: Display the last two rows.

Example:

In [ ]:
print(df.tail(2))

     name  study_hours  attendance  exam_score
2    John            2          70          58
3  Ayesha            6          95          94

Check your work:

- How many rows are shown?

__________

2

## 11. shape

shape returns a pair: (rows, columns).

In [ ]:
print(df.shape)
print('Rows:',df.shape[0])
print('Columns:',df.shape[1])

In [ ]:
print(marks.shape)

(3,)

In [ ]:
print(ls.shape)

(3, 3)

### Task 12: Find Dataset Size

Goal: Use shape to count rows and columns.

Example:

In [ ]:
print('Shape:',df.shape)

Shape: (4, 4)

Check your work:

- What is the number of rows?

- What is the number of columns?

__________

- 4 r
- 4 c

```code
mov [FFFE],0xDEA2
mov AX,0x213

```

## 12. columns

In [ ]:
print(df.columns)
print()
print(list(df.columns))

Index(['name', 'study_hours', 'attendance', 'exam_score'], dtype='object')

['name', 'study_hours', 'attendance', 'exam_score']

In [ ]:
list(ls.columns)

['brand', 'model', 'make']

In [ ]:
list(d)

['3', '3.1', '3.2', '3.3']

In [ ]:
list(d.columns)

['3', '3.1', '3.2', '3.3']

In [ ]:
list(ls)

['brand', 'model', 'make']

### Task 13: List Column Names

Goal: Display all column names.

Example:

In [ ]:
print(list(df.columns))

['name', 'study_hours', 'attendance', 'exam_score']

In [ ]:
list(df)

['name', 'study_hours', 'attendance', 'exam_score']

In [ ]:
list(df)

['name', 'study_hours', 'attendance', 'exam_score']

Check your work:

- Are the names clear and meaningful?

__________

- yes

## 13. info()

info() gives a compact summary of columns, non-null counts, and data types.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         4 non-null      object
 1   study_hours  4 non-null      int64
 2   attendance   4 non-null      int64
 3   exam_score   4 non-null      int64
dtypes: int64(3), object(1)
memory usage: 260.0+ bytes

In [ ]:
print(ls)

    brand   model  make
0  toyota  grende  2017
1   honda   civic  2010
2  suzuki   swift  2015

| AI connection: info() helps us notice text columns, missing values, and unexpected types before a model is trained. |
| --- |

### Task 14: Run info

Goal: Inspect the complete DataFrame summary.

Example:

In [ ]:
df.info()

Check your work:

- Which columns are numeric?

- Are any values missing?

- Which column is text?

__________

In [ ]:
ls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   brand   3 non-null      object
 1   model   3 non-null      object
 2   make    3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
ls

    brand   model  make
0  toyota  grende  2017
1   honda   civic  2010
2  suzuki   swift  2015

## 14. describe()

describe() provides summary statistics for numerical columns.

In [ ]:
print(df.describe())

- count = number of non-missing numeric values

- mean = average

- std = standard deviation

- min = smallest

- 25% = first quartile

- 50% = median

- 75% = third quartile

- max = largest

In [ ]:
ls.describe()

              make
count     3.000000
mean   2014.000000
std       3.605551
min    2010.000000
25%    2012.500000
50%    2015.000000
75%    2016.000000
max    2017.000000

### Task 15: Read describe

Goal: Use describe() and answer questions.

Example:

In [ ]:
print(df.describe())

Check your work:

- What is the average exam score?

- What is the minimum?

- What is the maximum?

__________

In [ ]:
ls.describe()

              make
count     3.000000
mean   2014.000000
std       3.605551
min    2010.000000
25%    2012.500000
50%    2015.000000
75%    2016.000000
max    2017.000000

In [ ]:
print("avg is 2014")
print("min is 2010")
print("max is 2017")

avg is 2014
min is 2010
max is 2017

## 15. Data Types

A data type tells us what kind of value is stored in a column. Common types include int64, float64, object/string, and bool.

In [ ]:
print(df.dtypes)

In [ ]:
ls.dtypes

brand    object
model    object
make      int64
dtype: object

### Task 16: Check Types

Goal: Print all column data types.

Example:

In [ ]:
print(df.dtypes)

Check your work:

- Which column is text?

- Which columns are numbers?

__________

In [ ]:
ls.dtypes

brand    object
model    object
make      int64
dtype: object

In [ ]:
print("first 2 are text \n last ist int64")

first 2 are text
 last ist int64

### Why Data Types Matter

- A number stored as text may not work in calculations.

- Dates may need date/time conversion.

- Many ML algorithms need numerical inputs.

- Wrong types can cause errors or incorrect results.

## 16. Main Practice Dataset

Create a file named student_performance.csv with the following data:

In [ ]:
%%writefile student_performance.csv
student_id,name,study_hours,attendance,assignment_score,exam_score
STU001,Ali,3,75,68,65
STU002,Sara,5,90,85,88
STU003,John,2,70,60,58
STU004,Ayesha,6,95,92,94
STU005,Bilal,4,80,75,73
STU006,Hina,7,98,90,96
STU007,Omar,1,65,55,50
STU008,Maryam,5,88,82,84

Writing student_performance.csv

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('student_performance.csv')
print(df)

  student_id    name  study_hours  attendance  assignment_score  exam_score
0     STU001     Ali            3          75                68          65
1     STU002    Sara            5          90                85          88
2     STU003    John            2          70                60          58
3     STU004  Ayesha            6          95                92          94
4     STU005   Bilal            4          80                75          73
5     STU006    Hina            7          98                90          96
6     STU007    Omar            1          65                55          50
7     STU008  Maryam            5          88                82          84

## 17. Initial Dataset Inspection

Use this order whenever you receive a new dataset:

1. Load the dataset.

2. Use head().

3. Use tail().

4. Check shape.

5. Check columns.

6. Run info().

7. Run describe().

8. Check dtypes.

9. Check missing values.

10. Check duplicates.

In [ ]:
df.head(3)

  student_id  name  study_hours  attendance  assignment_score  exam_score
0     STU001   Ali            3          75                68          65
1     STU002  Sara            5          90                85          88
2     STU003  John            2          70                60          58

In [ ]:
df.tail(2)

  student_id    name  study_hours  attendance  assignment_score  exam_score
6     STU007    Omar            1          65                55          50
7     STU008  Maryam            5          88                82          84

In [ ]:
df.shape

(8, 6)

In [ ]:
df.columns

Index(['student_id', 'name', 'study_hours', 'attendance', 'assignment_score',
       'exam_score'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        8 non-null      object
 1   name              8 non-null      object
 2   study_hours       8 non-null      int64
 3   attendance        8 non-null      int64
 4   assignment_score  8 non-null      int64
 5   exam_score        8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

In [ ]:
df.describe()

       study_hours  attendance  assignment_score  exam_score
count      8.00000    8.000000          8.000000    8.000000
mean       4.12500   82.625000         75.875000   76.000000
std        2.03101   11.999256         13.788582   17.163083
min        1.00000   65.000000         55.000000   50.000000
25%        2.75000   73.750000         66.000000   63.250000
50%        4.50000   84.000000         78.500000   78.500000
75%        5.25000   91.250000         86.250000   89.500000
max        7.00000   98.000000         92.000000   96.000000

In [ ]:
df.dtypes

student_id          object
name                object
study_hours          int64
attendance           int64
assignment_score     int64
exam_score           int64
dtype: object

In [ ]:
df.isna()

   student_id   name  study_hours  attendance  assignment_score  exam_score
0       False  False        False       False             False       False
1       False  False        False       False             False       False
2       False  False        False       False             False       False
3       False  False        False       False             False       False
4       False  False        False       False             False       False
5       False  False        False       False             False       False
6       False  False        False       False             False       False
7       False  False        False       False             False       False

In [ ]:
df.isnull()

   student_id   name  study_hours  attendance  assignment_score  exam_score
0       False  False        False       False             False       False
1       False  False        False       False             False       False
2       False  False        False       False             False       False
3       False  False        False       False             False       False
4       False  False        False       False             False       False
5       False  False        False       False             False       False
6       False  False        False       False             False       False
7       False  False        False       False             False       False

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

### Task 17: Complete First Inspection

Goal: Run all basic inspection commands.

Example:

In [ ]:
print(df.head())
print()
print(df.tail())
print()
print(df.shape)
print()
print(list(df.columns))
print()
df.info()
print()
print(df.describe())
print()
print(df.dtypes)

  student_id    name  study_hours  attendance  assignment_score  exam_score
0     STU001     Ali            3          75                68          65
1     STU002    Sara            5          90                85          88
2     STU003    John            2          70                60          58
3     STU004  Ayesha            6          95                92          94
4     STU005   Bilal            4          80                75          73

  student_id    name  study_hours  attendance  assignment_score  exam_score
3     STU004  Ayesha            6          95                92          94
4     STU005   Bilal            4          80                75          73
5     STU006    Hina            7          98                90          96
6     STU007    Omar            1          65                55          50
7     STU008  Maryam            5          88                82          84

(8, 6)

['student_id', 'name', 'study_hours', 'attendance', 'assignment_score', 'exam_score']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        8 non-null      object
 1   name              8 non-null      object
 2   study_hours       8 non-null      int64
 3   attendance        8 non-null      int64
 4   assignment_score  8 non-null      int64
 5   exam_score        8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

       study_hours  attendance  assignment_score  exam_score
count      8.00000    8.000000          8.000000    8.000000
mean       4.12500   82.625000         75.875000   76.000000
std        2.03101   11.999256         13.788582   17.163083
min        1.00000   65.000000         55.000000   50.000000
25%        2.75000   73.750000         66.000000   63.250000
50%        4.50000   84.000000         78.500000   78.500000
75%        5.25000   91.250000         86.250000   89.500000
max        7.00000   98.000000         92.000000   96.000000

student_id          object
name                object
study_hours          int64
attendance           int64
assignment_score     int64
exam_score           int64
dtype: object

Check your work:

- How many students?

- How many columns?

- Which column is the target?

__________

In [ ]:
len(df)

8

In [ ]:
len(df.columns)

6

## 18. Missing Values — Important Extra Topic

Real datasets often contain missing values. Always check them.

In [ ]:
print(df.isnull().sum())

student_id          0
name                0
study_hours         0
attendance          0
assignment_score    0
exam_score          0
dtype: int64

### Task 18: Check Missing Values

Goal: Find the number of missing values in each column.

Example:

In [ ]:
missing=df.isnull().sum()
print(missing)

student_id          0
name                0
study_hours         0
attendance          0
assignment_score    0
exam_score          0
dtype: int64

Check your work:

- Which column has the most missing values?

- Is the provided dataset complete?

__________

In [ ]:
"""non and yes"""

'non and yes'

## 19. Duplicate Rows — Important Extra Topic

In [ ]:
print('Duplicates:',df.duplicated().sum())

Duplicates: 0

### Task 19: Check Duplicates

Goal: Check whether any rows are repeated.

Example:

In [ ]:
print(df.duplicated().sum())

0

Check your work:

- How many duplicates?

- Why might duplicates cause problems?

__________

In [ ]:
"""non dups problems:  this can make model  baised to this       data"""

'non dups problems:  this can make model  baised to this       data'

## 20. Selecting Columns — Important Extra Topic

In [ ]:
print(df['exam_score'])
print()
print(df[['name','attendance','exam_score']])

0    65
1    88
2    58
3    94
4    73
5    96
6    50
7    84
Name: exam_score, dtype: int64

     name  attendance  exam_score
0     Ali          75          65
1    Sara          90          88
2    John          70          58
3  Ayesha          95          94
4   Bilal          80          73
5    Hina          98          96
6    Omar          65          50
7  Maryam          88          84

### Task 20: Select Columns

Goal: Display name and exam_score.

Example:

In [ ]:
print(df[['name','exam_score']])

     name  exam_score
0     Ali          65
1    Sara          88
2    John          58
3  Ayesha          94
4   Bilal          73
5    Hina          96
6    Omar          50
7  Maryam          84

Check your work:

- How many columns are displayed?

__________

In [ ]:
len(df[['name','exam_score']].columns)

2

## 21. Filtering Rows — Important Extra Topic

In [ ]:
print(df[df['exam_score']>=80])
print()
print(df[df['attendance']>=90])

  student_id    name  study_hours  attendance  assignment_score  exam_score
1     STU002    Sara            5          90                85          88
3     STU004  Ayesha            6          95                92          94
5     STU006    Hina            7          98                90          96
7     STU008  Maryam            5          88                82          84

  student_id    name  study_hours  attendance  assignment_score  exam_score
1     STU002    Sara            5          90                85          88
3     STU004  Ayesha            6          95                92          94
5     STU006    Hina            7          98                90          96

### Task 21: Filter Students

Goal: Display students with exam scores of at least 80.

Example:

In [ ]:
result=df[df['exam_score']>=80]
print(result)

  student_id    name  study_hours  attendance  assignment_score  exam_score
1     STU002    Sara            5          90                85          88
3     STU004  Ayesha            6          95                92          94
5     STU006    Hina            7          98                90          96
7     STU008  Maryam            5          88                82          84

Check your work:

- How many students meet the condition?

__________

In [ ]:
len(result)

4

## 22. Sorting — Important Extra Topic

In [ ]:
print(df.sort_values('exam_score',ascending=False))

  student_id    name  study_hours  attendance  assignment_score  exam_score
5     STU006    Hina            7          98                90          96
3     STU004  Ayesha            6          95                92          94
1     STU002    Sara            5          90                85          88
7     STU008  Maryam            5          88                82          84
4     STU005   Bilal            4          80                75          73
0     STU001     Ali            3          75                68          65
2     STU003    John            2          70                60          58
6     STU007    Omar            1          65                55          50

### Task 22: Sort Students

Goal: Sort students from highest to lowest exam score.

Example:

In [ ]:
top=df.sort_values('exam_score',ascending=False)
print(top[['name','exam_score']])

Check your work:

- Who is first?

- Who is last?

__________

In [ ]:
print(df.sort_values('exam_score',ascending=False)[['name','exam_score']])

     name  exam_score
5    Hina          96
3  Ayesha          94
1    Sara          88
7  Maryam          84
4   Bilal          73
0     Ali          65
2    John          58
6    Omar          50

In [ ]:
(df.sort_values('exam_score',ascending=False)[['name','exam_score']]).head(1)

   name  exam_score
5  Hina          96

In [ ]:
(df.sort_values('exam_score',ascending=False)[['name','exam_score']]).tail(1)

   name  exam_score
6  Omar          50

## 23. Simple Dataset Questions

11. How many students are in the dataset?

12. What is the average exam score?

13. Who has the highest exam score?

14. Who has the lowest exam score?

15. How many students have attendance of 90 or more?

16. How many students have study_hours >= 5?

## 24. Integrated Lab: AI Dataset Inspection

Imagine that an instructor gives you a new student dataset for an AI project. You are not allowed to train a model yet. First, prepare an inspection report.

In [ ]:
import pandas as pd

df = pd.read_csv('student_performance.csv')

print('--- HEAD ---')
print(df.head())
print()

print('--- TAIL ---')
print(df.tail())
print()

print('--- SHAPE ---')
print(df.shape)
print()

print('--- COLUMNS ---')
print(list(df.columns))
print()

print('--- INFO ---')
df.info()
print()

print('--- DESCRIBE ---')
print(df.describe())
print()

print('--- DTYPES ---')
print(df.dtypes)
print()

print('--- MISSING ---')
print(df.isnull().sum())
print()

print('--- DUPLICATES ---')
print(df.duplicated().sum())
print()

--- HEAD ---
  student_id    name  study_hours  attendance  assignment_score  exam_score
0     STU001     Ali            3          75                68          65
1     STU002    Sara            5          90                85          88
2     STU003    John            2          70                60          58
3     STU004  Ayesha            6          95                92          94
4     STU005   Bilal            4          80                75          73

--- TAIL ---
  student_id    name  study_hours  attendance  assignment_score  exam_score
3     STU004  Ayesha            6          95                92          94
4     STU005   Bilal            4          80                75          73
5     STU006    Hina            7          98                90          96
6     STU007    Omar            1          65                55          50
7     STU008  Maryam            5          88                82          84

--- SHAPE ---
(8, 6)

--- COLUMNS ---
['student_id', 'name', 'study_hours', 'attendance', 'assignment_score', 'exam_score']

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        8 non-null      object
 1   name              8 non-null      object
 2   study_hours       8 non-null      int64
 3   attendance        8 non-null      int64
 4   assignment_score  8 non-null      int64
 5   exam_score        8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

--- DESCRIBE ---
       study_hours  attendance  assignment_score  exam_score
count      8.00000    8.000000          8.000000    8.000000
mean       4.12500   82.625000         75.875000   76.000000
std        2.03101   11.999256         13.788582   17.163083
min        1.00000   65.000000         55.000000   50.000000
25%        2.75000   73.750000         66.000000   63.250000
50%        4.50000   84.000000         78.500000   78.500000
75%        5.25000   91.250000         86.250000   89.500000
max        7.00000   98.000000         92.000000   96.000000

--- DTYPES ---
student_id          object
name                object
study_hours          int64
attendance           int64
assignment_score     int64
exam_score           int64
dtype: object

--- MISSING ---
student_id          0
name                0
study_hours         0
attendance          0
assignment_score    0
exam_score          0
dtype: int64

--- DUPLICATES ---
0

### Task 23: Build the Inspection Report

Goal: Run the complete report and explain what you learned.

Example:

In [ ]:
# Run the complete program above

Check your work:

- Is the dataset complete?

- Which columns could be input features?

- Which column could be a target?

__________

In [ ]:
yes

In [ ]:
df.columns

Index(['student_id', 'name', 'study_hours', 'attendance', 'assignment_score',
       'exam_score'],
      dtype='object')

In [ ]:
print('study_hours', 'attendance', 'assignment_score')

('study_hours', 'attendance', 'assignment_score')

In [ ]:
'exam_score'

'exam_score'

## 25. Mini Project: Dataset Health Check

Write a reusable function that can inspect any small tabular dataset.

In [ ]:
def inspect_dataset(df):
    print('DATASET HEALTH CHECK')
    print('Rows:', df.shape[0])
    print('Columns:', df.shape[1])
    print('Column names:', list(df.columns))
    print('\nMissing values:')
    print(df.isnull().sum())
    print('\nDuplicate rows:')
    print(df.duplicated().sum())
    print('\nData types:')
    print(df.dtypes)
    print('\nFirst rows:')
    print(df.head())

inspect_dataset(df)

DATASET HEALTH CHECK
Rows: 8
Columns: 6
Column names: ['student_id', 'name', 'study_hours', 'attendance', 'assignment_score', 'exam_score']

Missing values:
student_id          0
name                0
study_hours         0
attendance          0
assignment_score    0
exam_score          0
dtype: int64

Duplicate rows:
0

Data types:
student_id          object
name                object
study_hours          int64
attendance           int64
assignment_score     int64
exam_score           int64
dtype: object

First rows:
  student_id    name  study_hours  attendance  assignment_score  exam_score
0     STU001     Ali            3          75                68          65
1     STU002    Sara            5          90                85          88
2     STU003    John            2          70                60          58
3     STU004  Ayesha            6          95                92          94
4     STU005   Bilal            4          80                75          73

### Task 24: Run the Health Check

Goal: Use the function on student_performance.csv.

Example:

In [ ]:
inspect_dataset(df)

DATASET HEALTH CHECK
Rows: 8
Columns: 6
Column names: ['student_id', 'name', 'study_hours', 'attendance', 'assignment_score', 'exam_score']

Missing values:
student_id          0
name                0
study_hours         0
attendance          0
assignment_score    0
exam_score          0
dtype: int64

Duplicate rows:
0

Data types:
student_id          object
name                object
study_hours          int64
attendance           int64
assignment_score     int64
exam_score           int64
dtype: object

First rows:
  student_id    name  study_hours  attendance  assignment_score  exam_score
0     STU001     Ali            3          75                68          65
1     STU002    Sara            5          90                85          88
2     STU003    John            2          70                60          58
3     STU004  Ayesha            6          95                92          94
4     STU005   Bilal            4          80                75          73

Check your work:

- What does shape[0] mean?

- What does shape[1] mean?

__________

In [6]:
print(df.shape)

(8, 6)

In [ ]:
df.shape[0]

8

In [ ]:
df.shape[1]

6

## 26. Final Challenge

Complete this challenge independently.

17. Load student_performance.csv.

18. Display the first five rows.

19. Display the last three rows.

20. Print shape.

21. Print column names.

22. Run info().

23. Run describe().

24. Print dtypes.

25. Check missing values.

26. Check duplicate rows.

27. Display name, study_hours, attendance, and exam_score.

28. Filter exam_score >= 80.

29. Sort by exam_score from highest to lowest.

30. Write three observations about the dataset.

In [ ]:
df = pd.read_csv('student_performance.csv')
df.head(5)

In [ ]:
df.tail(3)

In [ ]:
df.shape

In [ ]:
df.columns

Index(['student_id', 'name', 'study_hours', 'attendance', 'assignment_score',
       'exam_score'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        8 non-null      object
 1   name              8 non-null      object
 2   study_hours       8 non-null      int64
 3   attendance        8 non-null      int64
 4   assignment_score  8 non-null      int64
 5   exam_score        8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

In [ ]:
df.describe()

       study_hours  attendance  assignment_score  exam_score
count      8.00000    8.000000          8.000000    8.000000
mean       4.12500   82.625000         75.875000   76.000000
std        2.03101   11.999256         13.788582   17.163083
min        1.00000   65.000000         55.000000   50.000000
25%        2.75000   73.750000         66.000000   63.250000
50%        4.50000   84.000000         78.500000   78.500000
75%        5.25000   91.250000         86.250000   89.500000
max        7.00000   98.000000         92.000000   96.000000

In [ ]:
df.dtypes

student_id          object
name                object
study_hours          int64
attendance           int64
assignment_score     int64
exam_score           int64
dtype: object

In [ ]:
df.isna()

   student_id   name  study_hours  attendance  assignment_score  exam_score
0       False  False        False       False             False       False
1       False  False        False       False             False       False
2       False  False        False       False             False       False
3       False  False        False       False             False       False
4       False  False        False       False             False       False
5       False  False        False       False             False       False
6       False  False        False       False             False       False
7       False  False        False       False             False       False

In [ ]:
df.duplicated()

In [ ]:
df[['name', 'study_hours', 'attendance', 'exam_score']]

     name  study_hours  attendance  exam_score
0     Ali            3          75          65
1    Sara            5          90          88
2    John            2          70          58
3  Ayesha            6          95          94
4   Bilal            4          80          73
5    Hina            7          98          96
6    Omar            1          65          50
7  Maryam            5          88          84

In [ ]:
f=df[['name', 'study_hours', 'attendance', 'exam_score']]

In [ ]:
f.dtypes

name           object
study_hours     int64
attendance      int64
exam_score      int64
dtype: object

In [ ]:
f[f["exam_score"] >= 80]

     name  study_hours  attendance  exam_score
1    Sara            5          90          88
3  Ayesha            6          95          94
5    Hina            7          98          96
7  Maryam            5          88          84

In [ ]:
f.sort_values("exam_score",ascending=False)

     name  study_hours  attendance  exam_score
5    Hina            7          98          96
3  Ayesha            6          95          94
1    Sara            5          90          88
7  Maryam            5          88          84
4   Bilal            4          80          73
0     Ali            3          75          65
2    John            2          70          58
6    Omar            1          65          50

In [ ]:
"its a clean dataset with half people      having above 80 marks rest less"

'its a clean dataset with half people      having above 80 marks rest less'

---

# END OF DOCUMENT 1 — START OF DOCUMENT 2

# DOCUMENT 2 — ADVANCED PANDAS: Advanced Selection, Data Cleaning & GroupBy

*Source: `Advanced_Pandas_Lab_Manual_2_Hours.docx`*

*Original document footer: Introduction to Data Science — Advanced Pandas Lab*

**LAB MANUAL  
ADVANCED PANDAS**

**Advanced Selection, Data Cleaning & GroupBy**

## 1. Lab Overview

| Course | Introduction to Data Science |
| --- | --- |
| Topic | Advanced Pandas |
| Prerequisites | Series, DataFrame, rows/columns/index, CSV/JSON datasets, dataset paths |
| Software | Python 3.x, Jupyter Notebook / JupyterLab, Pandas |

Lab focus: Students will use Pandas to select and filter records, identify and clean common data-quality problems, and perform grouped analysis with groupby().

## 2. Learning Outcomes

- Use loc[] and iloc[] to select rows and columns.

- Apply Boolean conditions, isin(), between(), and query() for filtering.

- Detect and handle missing values and duplicate records.

- Inspect unique values, value counts, and data types.

- Use groupby() with common aggregation functions.

- Combine filtering, cleaning, and grouped analysis in one workflow.

## 3. Time Plan

| Activity | Time | Focus |
| --- | --- | --- |
| Setup & dataset inspection | 10 min | Load, inspect, understand data |
| Activity 1: Selection & filtering | 30 min | loc, iloc, Boolean filtering |
| Activity 2: Data cleaning | 30 min | Missing values, duplicates, categories |
| Activity 3: GroupBy | 30 min | Aggregation and grouped analysis |
| Integrated challenge | 15 min | Complete analysis workflow |

## 4. Dataset Preparation

Create a file named students.csv using the following data. The dataset intentionally contains missing values, duplicate records, and inconsistent department labels.

In [1]:
%%writefile students.csv
StudentID,Name,Age,Department,GPA,Fees
101,Ali,20,CS,3.20,85000
102,Sara,21,AI,3.70,90000
103,Ahmed,19,CS,2.80,82000
104,Hina,22,AI,3.50,90000
105,Usman,,SE,3.10,78000
106,Ayesha,23,cs,3.80,82000
107,Bilal,21,AI,,90000
108,Maria,24,SE,3.40,78000
109,Hamza,20,CS,3.00,85000
110,Zara,22,AI,3.90,90000
111,Ali,20,CS,3.20,85000
112,Noor,19,Computer Science,3.60,85000

Overwriting students.csv

The repeated Ali record is intentional. The values cs and Computer Science are also intentional examples of inconsistent category labels.

## 5. Setup and Initial Inspection

In [2]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df.head(),'\n')
print(df.shape,'\n')
print(df.columns,'\n')
print(df.dtypes,'\n')
print(df.info(),'\n')

   StudentID   Name   Age Department  GPA   Fees
0        101    Ali  20.0         CS  3.2  85000
1        102   Sara  21.0         AI  3.7  90000
2        103  Ahmed  19.0         CS  2.8  82000
3        104   Hina  22.0         AI  3.5  90000
4        105  Usman   NaN         SE  3.1  78000

(12, 6)

Index(['StudentID', 'Name', 'Age', 'Department', 'GPA', 'Fees'], dtype='object')

StudentID       int64
Name           object
Age           float64
Department     object
GPA           float64
Fees            int64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   12 non-null     int64
 1   Name        12 non-null     object
 2   Age         11 non-null     float64
 3   Department  12 non-null     object
 4   GPA         11 non-null     float64
 5   Fees        12 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 708.0+ bytes
None

Task 1: Before changing anything, answer: How many rows and columns are present? Which columns contain numerical data? Which columns are categorical?

In [9]:
print(df.shape)

(12, 6)

In [ ]:
df.dtypes

StudentID       int64
Name           object
Age           float64
Department     object
GPA           float64
Fees            int64
dtype: object

## 6. Activity 1 — Advanced Selection and Filtering

### 6.1 Selecting Columns

In [ ]:
df["GPA"]
df[["Name", "Department", "GPA"]]

      Name        Department  GPA
0      Ali                CS  3.2
1     Sara                AI  3.7
2    Ahmed                CS  2.8
3     Hina                AI  3.5
4    Usman                SE  3.1
5   Ayesha                cs  3.8
6    Bilal                AI  NaN
7    Maria                SE  3.4
8    Hamza                CS  3.0
9     Zara                AI  3.9
10     Ali                CS  3.2
11    Noor  Computer Science  3.6

Task 2: Display only Name, Age, and Department.

In [59]:
# Write your code here
print(df[["Name", "Department", "Age"]])

      Name        Department   Age
0      Ali                CS  20.0
1     Sara                AI  21.0
2    Ahmed                CS  19.0
3     Hina                AI  22.0
4    Usman                SE   NaN
5   Ayesha                cs  23.0
6    Bilal                AI  21.0
7    Maria                SE  24.0
8    Hamza                CS  20.0
9     Zara                AI  22.0
10     Ali                CS  20.0
11    Noor  Computer Science  19.0

### 6.2 loc() and iloc()

Task 3: Use loc[] to select the row whose index label is 4. Then use iloc[] to select the fifth row.

# loc  
# Write your code here  
  
# iloc  
# Write your code here

Remember: loc[] uses labels; iloc[] uses integer positions.

In [ ]:
df.loc[4]

StudentID       105
Name          Usman
Age             NaN
Department       SE
GPA             3.1
Fees          78000
Name: 4, dtype: object

In [ ]:
df.iloc[4]

StudentID       105
Name          Usman
Age             NaN
Department       SE
GPA             3.1
Fees          78000
Name: 4, dtype: object

### 6.3 Boolean Filtering

Task 4: Find all students whose GPA is greater than 3.5.

In [ ]:
df[df["GPA"] > 3.5]

    StudentID    Name  Age        Department  GPA   Fees
1         102    Sara  3.7                AI  3.7  90000
5         106  Ayesha  3.8                cs  3.8  82000
9         110    Zara  3.9                AI  3.9  90000
11        112    Noor  3.6  Computer Science  3.6  85000

Task 5: Find students whose Age is at least 21.

In [13]:
# Write your code here
print(df[df["Age"]>=21])

   StudentID    Name   Age Department  GPA   Fees
1        102    Sara  21.0         AI  3.7  90000
3        104    Hina  22.0         AI  3.5  90000
5        106  Ayesha  23.0         cs  3.8  82000
6        107   Bilal  21.0         AI  NaN  90000
7        108   Maria  24.0         SE  3.4  78000
9        110    Zara  22.0         AI  3.9  90000

In [14]:
print(df.columns)

Index(['StudentID', 'Name', 'Age', 'Department', 'GPA', 'Fees'], dtype='object')

In [ ]:
df[df["Age"] >= 3]#21

    StudentID    Name  Age        Department  GPA   Fees
0         101     Ali  3.2                CS  3.2  85000
1         102    Sara  3.7                AI  3.7  90000
3         104    Hina  3.5                AI  3.5  90000
4         105   Usman  3.1                SE  3.1  78000
5         106  Ayesha  3.8                cs  3.8  82000
6         107   Bilal  3.4                AI  3.4  90000
7         108   Maria  3.4                SE  3.4  78000
9         110    Zara  3.9                AI  3.9  90000
10        111     Ali  3.2                CS  3.2  85000
11        112    Noor  3.6  Computer Science  3.6  85000

Task 6: Find students who are in AI and have GPA greater than 3.5.

In [ ]:
# Write your code here

In [16]:
print(df[(df["Department"] == "AI") & (df["GPA"]>3.5)])

   StudentID  Name   Age Department  GPA   Fees
1        102  Sara  21.0         AI  3.7  90000
9        110  Zara  22.0         AI  3.9  90000

Task 7: Find students from either AI or CS.

In [ ]:
# Write your code here

In [17]:
print(df[(df["Department"] == "AI") | (df["Department"] =="CS")])

    StudentID   Name   Age Department  GPA   Fees
0         101    Ali  20.0         CS  3.2  85000
1         102   Sara  21.0         AI  3.7  90000
2         103  Ahmed  19.0         CS  2.8  82000
3         104   Hina  22.0         AI  3.5  90000
6         107  Bilal  21.0         AI  NaN  90000
8         109  Hamza  20.0         CS  3.0  85000
9         110   Zara  22.0         AI  3.9  90000
10        111    Ali  20.0         CS  3.2  85000

### 6.4 isin() and between()

Task 8: Use isin() to select students from AI, CS, or SE.

In [ ]:
# Write your code here

In [19]:
print(df[df["Department"].isin(["AI","SE","CS"])])

    StudentID   Name   Age Department  GPA   Fees
0         101    Ali  20.0         CS  3.2  85000
1         102   Sara  21.0         AI  3.7  90000
2         103  Ahmed  19.0         CS  2.8  82000
3         104   Hina  22.0         AI  3.5  90000
4         105  Usman   NaN         SE  3.1  78000
6         107  Bilal  21.0         AI  NaN  90000
7         108  Maria  24.0         SE  3.4  78000
8         109  Hamza  20.0         CS  3.0  85000
9         110   Zara  22.0         AI  3.9  90000
10        111    Ali  20.0         CS  3.2  85000

Task 9: Use between() to select students aged 20 to 22.

In [ ]:
# Write your code here

In [21]:
print(df[df["Age"].between(20,22)])

    StudentID   Name   Age Department  GPA   Fees
0         101    Ali  20.0         CS  3.2  85000
1         102   Sara  21.0         AI  3.7  90000
3         104   Hina  22.0         AI  3.5  90000
6         107  Bilal  21.0         AI  NaN  90000
8         109  Hamza  20.0         CS  3.0  85000
9         110   Zara  22.0         AI  3.9  90000
10        111    Ali  20.0         CS  3.2  85000

### 6.5 query()

Task 10: Use query() to find students with GPA above 3.0 and Fees equal to 90000.

In [ ]:
# Write your code here

In [23]:
print(df.query("GPA > 3.0 and Fees == 90000"))

   StudentID  Name   Age Department  GPA   Fees
1        102  Sara  21.0         AI  3.7  90000
3        104  Hina  22.0         AI  3.5  90000
9        110  Zara  22.0         AI  3.9  90000

## 7. Activity 2 — Data Cleaning

### 7.1 Finding Missing Values

In [28]:
print(df.isna())

    StudentID   Name    Age  Department    GPA   Fees
0       False  False  False       False  False  False
1       False  False  False       False  False  False
2       False  False  False       False  False  False
3       False  False  False       False  False  False
4       False  False   True       False  False  False
5       False  False  False       False  False  False
6       False  False  False       False   True  False
7       False  False  False       False  False  False
8       False  False  False       False  False  False
9       False  False  False       False  False  False
10      False  False  False       False  False  False
11      False  False  False       False  False  False

In [25]:
df.isna()
df.isna().sum()

StudentID     0
Name          0
Age           1
Department    0
GPA           1
Fees          0
dtype: int64

In [30]:
print(df.isna().sum().sum())

2

Task 11: Identify which columns contain missing values and how many missing values each column has.

In [ ]:
# Write your code here

In [34]:
df.isna().sum()

StudentID     0
Name          0
Age           1
Department    0
GPA           1
Fees          0
dtype: int64

### 7.2 Handling Missing GPA

Task 12: Calculate the mean GPA and use it to fill the missing GPA value.

In [ ]:
mean_gpa = df["GPA"].mean()
df["GPA"] = df["GPA"].fillna(mean_gpa)

Task 13: Verify that GPA no longer contains missing values.

In [ ]:
df.isna().sum()

### 7.3 Handling Missing Age

Task 14: Fill the missing Age using the median age.

In [35]:
median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)

In [36]:
median_age

21.0

In [37]:
df.isna().sum()

StudentID     0
Name          0
Age           0
Department    0
GPA           1
Fees          0
dtype: int64

In [38]:
median_age = df["GPA"].median()
df["GPA"] = df["GPA"].fillna(median_age)

In [40]:
print(df)

    StudentID    Name   Age        Department  GPA   Fees
0         101     Ali  20.0                CS  3.2  85000
1         102    Sara  21.0                AI  3.7  90000
2         103   Ahmed  19.0                CS  2.8  82000
3         104    Hina  22.0                AI  3.5  90000
4         105   Usman  21.0                SE  3.1  78000
5         106  Ayesha  23.0                cs  3.8  82000
6         107   Bilal  21.0                AI  3.4  90000
7         108   Maria  24.0                SE  3.4  78000
8         109   Hamza  20.0                CS  3.0  85000
9         110    Zara  22.0                AI  3.9  90000
10        111     Ali  20.0                CS  3.2  85000
11        112    Noor  19.0  Computer Science  3.6  85000

Why might median be preferable to mean when a variable contains extreme values?

### 7.4 Finding Duplicates

In [42]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [41]:
df.duplicated()
df.duplicated().sum()

np.int64(0)

Task 15: Remove duplicate records and store the cleaned result back in df.

In [ ]:
# Write your code here

In [ ]:
df.duplicated().sum()

In [46]:
print(df.drop_duplicates())

    StudentID    Name   Age        Department  GPA   Fees
0         101     Ali  20.0                CS  3.2  85000
1         102    Sara  21.0                AI  3.7  90000
2         103   Ahmed  19.0                CS  2.8  82000
3         104    Hina  22.0                AI  3.5  90000
4         105   Usman  21.0                SE  3.1  78000
5         106  Ayesha  23.0                cs  3.8  82000
6         107   Bilal  21.0                AI  3.4  90000
7         108   Maria  24.0                SE  3.4  78000
8         109   Hamza  20.0                CS  3.0  85000
9         110    Zara  22.0                AI  3.9  90000
10        111     Ali  20.0                CS  3.2  85000
11        112    Noor  19.0  Computer Science  3.6  85000

### 7.5 Checking Category Consistency

In [48]:
print(df["Department"].unique())

['CS' 'AI' 'SE' 'cs' 'Computer Science']

In [49]:
print(df["Department"].value_counts())

Department
CS                  4
AI                  4
SE                  2
cs                  1
Computer Science    1
Name: count, dtype: int64

Task 16: Identify the inconsistent department labels. Standardize cs as CS and Computer Science as CS.

In [ ]:
# Write your code here

In [64]:
df["Department"] = df['Department'].str.replace('cs','CS').str.replace('Computer Science',"CS")

In [66]:
print(df)

    StudentID    Name   Age Department  GPA   Fees
0         101     Ali  20.0         CS  3.2  85000
1         102    Sara  21.0         AI  3.7  90000
2         103   Ahmed  19.0         CS  2.8  82000
3         104    Hina  22.0         AI  3.5  90000
4         105   Usman   NaN         SE  3.1  78000
5         106  Ayesha  23.0         CS  3.8  82000
6         107   Bilal  21.0         AI  NaN  90000
7         108   Maria  24.0         SE  3.4  78000
8         109   Hamza  20.0         CS  3.0  85000
9         110    Zara  22.0         AI  3.9  90000
10        111     Ali  20.0         CS  3.2  85000
11        112    Noor  19.0         CS  3.6  85000

Task 17: Run value_counts() again and verify the result.

In [67]:
print(df.value_counts())

StudentID  Name    Age   Department  GPA  Fees
101        Ali     20.0  CS          3.2  85000    1
102        Sara    21.0  AI          3.7  90000    1
103        Ahmed   19.0  CS          2.8  82000    1
104        Hina    22.0  AI          3.5  90000    1
106        Ayesha  23.0  CS          3.8  82000    1
108        Maria   24.0  SE          3.4  78000    1
109        Hamza   20.0  CS          3.0  85000    1
110        Zara    22.0  AI          3.9  90000    1
111        Ali     20.0  CS          3.2  85000    1
112        Noor    19.0  CS          3.6  85000    1
Name: count, dtype: int64

## 8. Activity 3 — Grouping and Aggregation

### 8.1 Basic GroupBy

Task 18: Calculate the average GPA for each department.

In [72]:
print(df.groupby("Department")["GPA"].mean())

Department
AI    3.700000
CS    3.266667
SE    3.250000
Name: GPA, dtype: float64

In [70]:
df.groupby("Department")["GPA"].mean()

Department
AI    3.700000
CS    3.266667
SE    3.250000
Name: GPA, dtype: float64

Task 19: Calculate the number of students in each department.

In [ ]:
# Write your code here

In [80]:
print(df.groupby("Department").size())

Department
AI    4
CS    6
SE    2
dtype: int64

Task 20: Calculate total fees collected from each department.

In [ ]:
# Write your code here

In [81]:
df.groupby("Department")["Fees"].sum()

Department
AI    360000
CS    504000
SE    156000
Name: Fees, dtype: int64

### 8.2 Multiple Aggregations

Task 21: For each department, calculate the mean, minimum, and maximum GPA.

In [ ]:
# Write your code here

In [82]:
df.groupby("Department")["GPA"].mean()

Department
AI    3.700000
CS    3.266667
SE    3.250000
Name: GPA, dtype: float64

In [83]:
df.groupby("Department")["GPA"].min()

Department
AI    3.5
CS    2.8
SE    3.1
Name: GPA, dtype: float64

In [84]:
df.groupby("Department")["GPA"].max()

Department
AI    3.9
CS    3.8
SE    3.4
Name: GPA, dtype: float64

Task 22: For each department, calculate average Age and average GPA.

In [87]:
# Write your code here
df.groupby("Department")["Age"].mean()

Department
AI    21.500000
CS    20.166667
SE    24.000000
Name: Age, dtype: float64

In [86]:
df.groupby("Department")["GPA"].mean()

Department
AI    3.700000
CS    3.266667
SE    3.250000
Name: GPA, dtype: float64

### 8.3 Sorting Grouped Results

Task 23: Sort departments by average GPA from highest to lowest.

In [ ]:
# Write your code here

In [95]:
df.groupby("Department")["GPA"].mean().sort_values(ascending=False)

Department
AI    3.700000
CS    3.266667
SE    3.250000
Name: GPA, dtype: float64

## 9. Integrated Challenge — Clean and Analyze

Complete the following without copying a complete solution from the previous activities.

- Load students.csv into a DataFrame.

- Inspect its shape, columns, data types, missing values, and duplicates.

- Remove duplicate records.

- Fill missing Age using the median.

- Fill missing GPA using the mean.

- Standardize department names.

- Find students with GPA >= 3.5.

- Calculate student count by department.

- Calculate average GPA by department.

- Calculate total fees by department.

- Sort the departments by average GPA.

Final question: What conclusions can you draw about the departments from the cleaned dataset? Write 3–4 observations in your notebook.

## 10. Optional Extension

If you finish early, add a new column showing the average GPA of the student's department.

In [3]:
df["Department_Avg_GPA"] = (
    df.groupby("Department")["GPA"]
      .transform("mean").round(2)
)

print(df)

    StudentID    Name   Age        Department  GPA   Fees  Department_Avg_GPA
0         101     Ali  20.0                CS  3.2  85000                3.05
1         102    Sara  21.0                AI  3.7  90000                3.70
2         103   Ahmed  19.0                CS  2.8  82000                3.05
3         104    Hina  22.0                AI  3.5  90000                3.70
4         105   Usman   NaN                SE  3.1  78000                3.25
5         106  Ayesha  23.0                cs  3.8  82000                3.80
6         107   Bilal  21.0                AI  NaN  90000                3.70
7         108   Maria  24.0                SE  3.4  78000                3.25
8         109   Hamza  20.0                CS  3.0  85000                3.05
9         110    Zara  22.0                AI  3.9  90000                3.70
10        111     Ali  20.0                CS  3.2  85000                3.05
11        112    Noor  19.0  Computer Science  3.6  85000                3.60

Then create a column called Above_Department_Average that contains True when a student's GPA is above their department average.

In [98]:
d=df

In [7]:
print(df.query("Department_Avg_GPA < GPA"))

    StudentID   Name   Age Department  GPA   Fees  Department_Avg_GPA  \
0         101    Ali  20.0         CS  3.2  85000                3.05
7         108  Maria  24.0         SE  3.4  78000                3.25
9         110   Zara  22.0         AI  3.9  90000                3.70
10        111    Ali  20.0         CS  3.2  85000                3.05

    Above_Department_Average
0                       True
7                       True
9                       True
10                      True

In [6]:
df["Above_Department_Average"] =df["GPA"]>df["Department_Avg_GPA"]

In [8]:
print(df)

    StudentID    Name   Age        Department  GPA   Fees  Department_Avg_GPA  \
0         101     Ali  20.0                CS  3.2  85000                3.05
1         102    Sara  21.0                AI  3.7  90000                3.70
2         103   Ahmed  19.0                CS  2.8  82000                3.05
3         104    Hina  22.0                AI  3.5  90000                3.70
4         105   Usman   NaN                SE  3.1  78000                3.25
5         106  Ayesha  23.0                cs  3.8  82000                3.80
6         107   Bilal  21.0                AI  NaN  90000                3.70
7         108   Maria  24.0                SE  3.4  78000                3.25
8         109   Hamza  20.0                CS  3.0  85000                3.05
9         110    Zara  22.0                AI  3.9  90000                3.70
10        111     Ali  20.0                CS  3.2  85000                3.05
11        112    Noor  19.0  Computer Science  3.6  85000                3.60

    Above_Department_Average
0                       True
1                      False
2                      False
3                      False
4                      False
5                      False
6                      False
7                       True
8                      False
9                       True
10                      True
11                     False

## 11. Expected Skills Checklist

- □ Select one or multiple columns

- □ Use loc[]

- □ Use iloc[]

- □ Filter using Boolean conditions

- □ Use isin()

- □ Use between()

- □ Use query()

- □ Detect missing values

- □ Fill missing values

- □ Detect and remove duplicates

- □ Inspect unique categorical values

- □ Use value_counts()

- □ Use groupby()

- □ Apply aggregation functions

- □ Sort grouped results

- □ Interpret grouped statistics

## 12. Short Viva / Discussion Questions

1. What is the difference between loc[] and iloc[]?

2. Why can loc[2] and iloc[2] return different rows?

3. What is the difference between dropna() and fillna()?

4. Why should duplicate records be checked before analysis?

5. What does value_counts() tell us?

6. What does groupby() do?

7. What is the difference between mean(), count(), and sum() after groupby()?

8. Why is data cleaning performed before final analysis?

## 13. Lab Submission

Submit one Jupyter Notebook (.ipynb) containing:

- All code cells used in the lab.

- Outputs for the main activities.

- Answers to the integrated challenge.

- Three to four written observations from the cleaned dataset.

- Answers to the short viva/discussion questions.